//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ess_api.Core.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class essEntities1 : DbContext
    {
        public essEntities1()
            : base("name=essEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<article> articles { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<language> languages { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<product_copy1> product_copy1 { get; set; }
        public virtual DbSet<right> rights { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<role_has_right> role_has_right { get; set; }
        public virtual DbSet<translation> translations { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
