//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ess_api.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_copy1
    {
        public long Id { get; set; }
        public long category_Id { get; set; }
        public string name_t { get; set; }
        public string description { get; set; }
    
        public virtual category category { get; set; }
    }
}
