//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ess_api.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class translation
    {
        public int Id { get; set; }
        public string text { get; set; }
        public long language_Id { get; set; }
        public string key { get; set; }
    
        public virtual language language { get; set; }
    }
}
