//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ess_api.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public long Id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int status { get; set; }
        public sbyte hidden { get; set; }
        public Nullable<System.DateTime> createdAtDate { get; set; }
        public Nullable<System.DateTime> correctedAtDate { get; set; }
        public string title { get; set; }
        public string email { get; set; }
        public sbyte sendEmail { get; set; }
        public int department_Id { get; set; }
        public long role_Id { get; set; }
        public string fb_Id { get; set; }
        public string google_Id { get; set; }
    
        public virtual role role { get; set; }
    }
}
