// <auto-generated />
namespace ess_api.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Initial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initial));

        string IMigrationMetadata.Id
        {
            get { return "201807281629449_Initial"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
